// if you checked "fancy-settings" in extensionizr.com, uncomment this lines

//var settings = new Store("settings", {
  //   "sample_setting": "This is how you use Store.js to remember values"
 //});
var tablink;
var repo;

var re = new RegExp("https://github.com/(.*)/(.*)")

var github = new Github({
  token: "9916b85f384097134bf3ce762d3acc923b067939 ",
  auth: "oauth"
});

chrome.pageAction.onClicked.addListener(function(tab) {
	var splitLink = tablink.split("https://github.com")[1];
	var username = splitLink.split("/")[1];
	var repoName = splitLink.split("/")[2];
	var travisBuildLink = "https://travis-ci.org/Jack-Collins/" + repoName;
	repo = github.getRepo(username, repoName);
	try{
		//fork the repo
		repo.fork(function(err) {console.log(err)});
		fork = github.getRepo("Jack-Collins", repoName);
		//repo.deleteRepo(function(err, res){console.log(res)})
		var options = {
			"name" : "travis",
		"config" : {
					"user" : "Jack-Collins",
					"token" : "9916b85f384097134bf3ce762d3acc923b067939",
					"domain" : "http://notify.travis-ci.org",
					"content_type": "json"
					},
		"events" : ["push", "pull_request"],
		"active" : true
		}
		//create the git-travis hook
		try{fork.createHook(options, function(){
			console.log("this is a callback...");
		});}
		catch(err){console.log(err);}
		//initial commit to trigger build
		//fork.branch("branchToTriggerBuild2", function(err) {console.log(err)});
		/*var pull = {
			title: "test",
			body: "This pull request has been automatically generated by Prose.io.",
			base: "master",
			head: "branchToTriggerBuild"
		};
		repo.createPullRequest(pull, function(err, pullRequest) {});
*/
		//fork.write('master', 'ffyfy', 'language: java', 'YOUR_COMMIT_MESSAGE', function(err) {});
		
		//direct user to edit/creation link
		var ymlURL = "https://github.com/Jack-Collins/" + repoName + "/edit/master/.travis.yml";
		var travisYmlURL = travisYmlURLConfig(ymlURL, repoName);
		console.log("I can do what I like with the repo here of values: " + username +  "/" + repoName);
		console.log("travisBuildLink: " + travisBuildLink);

	}
	catch(err1){
		console.log(err1);
		}
		//open the relevant .travis.yml editor link
		chrome.tabs.create({
		'url' : travisYmlURL,
		'selected' : true
	}, function(tab) {
	});
		//open the build link
	chrome.tabs.create({
		'url' : travisBuildLink + "/branches",
		'selected' : true
	}, function(tab) {
	});
});

 function checkForValidUrl(tabId, changeInfo, tab) {
	if (re.test(tab.url)) {
		chrome.pageAction.show(tabId);
		tablink = tab.url;	
	}
};

 // Checks for URL change
chrome.tabs.onUpdated.addListener(checkForValidUrl);

//example of using a message handler from the inject scripts
chrome.extension.onMessage.addListener(
  function(request, sender, sendResponse) {
  	chrome.pageAction.show(sender.tab.id);
    sendResponse();
  });
  
function travisYmlURLConfig(url, repoName) {
    var http = new XMLHttpRequest();
    http.open('HEAD', url, false);
    http.send();
    if (http.status != 404)
        return url;
    else
        return "https://github.com/Jack-Collins/" + repoName + "/new/master?filename=.travis.yml";
}
